### ISSUE TITLE
Plugin does not like files with "hard" TABs

### ISSUE THREAD

**Issue by BlaM** [klorenz/atom-regex-railroad-diagrams#78] opened 2016-08-31 08:40 UTC
To reproduce...
- Go to Atom / Settings / Tab Type and set to "hard", i.e. Tab-Character (ASCII 9) will be put into files.
- create a new file "test.js"
- enter `var asd = /asd(foo)/;`

Now if you move the cursor into the regular expression everything is fine.
- move cursor between the "=" and the "/" and press TAB twice

Now if you move the cursor into the regular expression it will break.

This probably causes #77.

**Comment by stugol** [comment] 2016-09-01 19:50
Yes, that seems to be the cause. Any chance of a fix? I use this extension a lot.

**Comment by klorenz** [comment] 2017-06-26 21:40
Hi @BlaM , this should be fixed by latest release.  

I had a workaround, which fixed #58 in the past, when an atom API function did not return correct values (bufferRangeForScopeAtPosition and bufferRangeForScopeAtCursor).  This workaround did some calculation with the tabs, which obviously did not work in all cases.

Luckily, the workaround is not needed anymore, because the functions now return correct values (as far I have seen by now).

Best regards

**Closed by klorenz** 2017-06-26 21:40 UTC
